class TextCleaner {
  String cleanText(String text, {String language = "de"}) {

    Map<String, String> replacements = {
      "Destament": "Testament",
      "Gigali": "Kigali",
      "Parosin": "Parousie",
      "Sackman": "Sothman",
      "Lothar": "Luther ",
      "Franco": "Frank",
      "Crephod": "Krefeld",
      "Grefeld": "Krefeld",
      "Kefeld": "Krefeld",
      "Fizek": "Vitsek",
      "Ámen": "Amen",
      "...": "…",
    };
    Map<String, String> replacements_sk = {
      "Amin": "Amen",
      "klasifikovať": "zaradiť",
      "[Heb ": "[Žd ",
      "Aleluja": "Haleluja",
      "znášal hriech": "niesol hriech",
      "Drahí,": "Vy milí,",
      "Hebrejom": "Židom",
      "ohromení": "premožení",
      "Ohromuje": "Premáha",
      "pasáží": "miest",
      "pasáže": "miesta",
      "posledných čias": "konečného času",
      "posledných časov": "konečného času",
      "prostredníctvom": "skrze",
      "úryvkami": "miestami",
      "úryvky": "miesta",
      "úryvok": "miesto",
      "úvahách o slove": "preberaní Slova",
      ". Viete, ": ". Vy viete, že ",
      "konkrétne": "obzvlášť",
      " sa píše ": " stojí ",
      "Čítala som ďalej": "Čítam ďalej",
      "želám": "prajem",
      "Želám": "Prajem",
      "milosťou": "z milosti",
      " obetu ": " obeť ",
      "sa páči": "je ľúba",
      " sa mu páčili": " sme boli jemu ľúby",
      "v drahom Pánovom mene": "v drahom mene Pána",
      "túto dobu": "tento čas",
      "tejto doby": "tohto času",
      "tejto dobe": "tomto čase",
      "refrén": "chorus",
      "úryvkov": "miest",
      "prisľú": "zasľú",
      "povolal k existencii": "povolal do existencie",
      "posolstvo o konci sveta": "zvesť konečného času",
      " ohlasova": " zvestova",
      " ohlasuj": " zvestuj",
      "Kalvárii": "Golgote",
      "Kalváriu": "Golgotu",
      "Kalvárie": "Golgoty",
      "kalvársk": "golgotsk",
      "zážitky": "prežitia",
      " zažív": " prežív",
      " zažil": " prežil",
      " zažíval": " prežíval",
      " zažíva": " prežíva",
      " zažívali": " prežívali",
      " zažívala": " prežívala",
      " zažívalo": " prežívalo",
      "prekliaty": "zlorečený",
      "Prekliaty": "Zlorečený",
      "kliatbu": "zlorečenstvo",
      "Kliatbu": "Zlorečenstvo",
      "prekliatia": "zlorečenstva",
      "Prekliatia": "Zlorečenstva",
      "kliatby": "zlorečenstvá",
      "Kliatby": "Zlorečenstvá",
      "prekliatie": "zlorečenstvo",
      "Prekliatie": "Zlorečenstvo",
      "zchromáždění": "zhromáždění",
      "srovážení": "zhromážděni",
      " pánu ": " Pánu ",
      " pána ": " Pána ",
      "boží": "Boží",
      " trahé ": " drahé ",
      "Boží slovo": "Boží Slovo",
      "väčšiný": "večný",
      "Božým slobom": "Božím Slovom",
      "Božie slobo": "Božie Slovo",
      "Božie slovo": "Božie Slovo",
      "Božieho slova": "Božieho Slova",
      "Včítajme": "Čítajme",
      "posveteni": "posväteni",
      "posvetený": "posvätený",
      "Sväté písmo": "Sväté Písmo",
      " sveté ": " sväté ",
      "Milovaní,": "Vy milí,",
      "udelí milosť": "daruje milosť",
      "prostredníctvom milosti": "z milosti",
      " Amin": " Amen",
      "cirkev živého Boha": "Cirkev živého Boha",
      "cirkev Ježiša": "Cirkev Ježiša",
      "cirkvi živého Boha": "Cirkvi živého Boha",
      "cirkvi Ježiša": "Cirkvi Ježiša",
      "cirkvou živého Boha": "Cirkvou živého Boha",
      "cirkvou Ježiša": "Cirkvou Ježiša",
      "jeho slove": "jeho Slove",
      "Božom slove": "Božom Slove",
      "Božiemu slovu": "Božiemu Slovu",
      "Božím slovom": "Božím Slovom",
      "jeho slovom": "jeho Slovom",
      "svojím slovom": "svojím Slovom",
      "sväté slovo": "sväté Slovo",
      "Prečítajme": "Čítajme",
      "prečítajme": "čítajme",
      "Božie posolstvo": "Božiu zvesť",
      "bulletin": "obežník",
      "modlitbové": "modlitebné",
      "Najsil": "Najmoc",
      "najsil": "najmoc",
      "prísľub": "zasľúbenie",
      "posolstvu": "zvesti",
      "posolstvo ": "zvesť ",
      "Postavme sa ": "Povstaňme ",
      " omyle ": " blude ",
      " omyl ": " blud ",
      " urobil ": " vykonal ",
      " robí ": " koná ",
    };
    Map<String, String> replacements_en = {
      "Elia": "Elijah",
      "God's word": "God's Word",
      "word of God": "Word of God",
      "holy word": "holy Word",
      "his word": "his Word",
      "world prophet": "Word-Prophet",
      "word of truth": "Word of truth",
    };
    Map<String, String> replacements_de = {
      "Dienstwohler Prenhems": "Diens Bruder Branhams",
      "Stück Werk": "Stückwerk",
      "biete dich an": "bete dich an",
      "Wuderos": "Bruder Russ",
      "Wodoros": "Bruder Russ",
      "okkumenisch": "ökumenisch",
      "Siebentonner": "Sieben Donner",
      "Bruder Brenn ": "Bruder Branham ",
      "aus Gnaten": "aus Gnaden",
      "in bezug": "in Bezug",
      "Kumeni": "Chomeini",
      "Petros": "Petrus",
      "Talser": "Tulsa",
      "Insel Padmos": "Insel Patmos",
      " wählten Uhr": " Weltenuhr",
      "heilige Schrift": "Heilige Schrift",
      "zurückgelehrter": "Schriftgelehrter",
      "wohler Prenhems": "Bruder Branhams",
      "Bruderbrennhems": "Bruder Branhams",
      "Bude Brennhem": "Bruder Branham",
      "Buddha Branhams": "Bruder Branhams",
      "Buddha Branham": "Bruder Branham",
      "Bruder Brünnen": "Bruder Branham",
      "Buddha": "Bruder",
      "himmlische Erde": "himmlische Örter",
      "verborgenen Manner": "verborgenen Manna",
      "Gott sammte": "Gott sandte",
      "Gottes Kunde tut": "Gott es kundtut",
      "konton": "kundtun",
      " sandet ": " sandte ",
      "aufstehen und bieten": "aufstehen und beten",
      " sandest": " sandtest",
      "Städte zu bereiten": "Stätte zu bereiten",
      " erlieben": " erleben",
      "Laoducea": "Laodizea",
      "Laudezehr": "Laodizea",
      "Pflistern ": "Philistern ",
      "Pfilister ": "Philister ",
      "Philippa ": "Philipper ",
      "Philippa,": "Philipper, ",
      "Philippabrief,": "Philipperbrief, ",
      " rüben ": " rühmen ",
      "Preisel ": "Preise ",
      " Noas": " Noahs",
      "bieten dich an": "beten dich an",
      "Sohnestellung": "Sohnesstellung",
      "Herr Silber": "Herr Selber",
      "das Silbe": "das Selbe",
      "Das Silbe": "Das Selbe",
      "Bergetzion": "Berge Sion",
      "hersprach": "Herr sprach",
      "preis und ehre": "Preis und Ehre",
      "Verlegnung": "Vollendung",
      "wohlgewillt": "wohlgefällt",
      "auszuhören": "auszuführen",
      "Feinsagung": "Weissagung",
      "unvolles Genüge": "und volles Genüge",
      "Prophetenmott": "Prophetenmund",
      "Cherobe": "Cherube",
      "Bundeslatte": "Bundeslade",
      "Bundeslage": "Bundeslade",
      "Gelöbte": "Gelübde",
      "Handumdringen": "Handumdrehen",
      "manchelei": "mancherlei",
      "zügelos": "zügellos",
      "gesöhnt": "gesühnt",
      "Passalam": "Passahlamm",
      "Anblitz": "Antlitz",
      "zurückerstanden": "zurückerstatten",
      "Ehefurcht": "Ehrfurcht",
      " geweiss sagt": " geweissagt",
      "wahrhaftig ungerecht": "wahrhaftig und gerecht",
      "Gericht und Treu": "gerecht und treu",
      "geweißackt": "geweissagt",
      "Siegensverheißung": "Segensverheißung",
      "allesirdischen": "alles Irdischen",
      "da zu sitzen": "dazusitzen",
      "zuteil geworden": "zuteilgeworden",
      "Hebräer brief": "Hebräer-Brief",
      "Präabrief": "Hebräer-Brief",
      "Emmausjüngern": "Emmaus-Jüngern",
      "Jahr aus und Jahr ein": "jahraus und jahrein",
      "Halotria": "Hallodria Leichtsinn, Unzuverlässigkeit",
      "Fasson": "Fasson Fassung",
      "Heiljahr": "Halljahr",
      "Chirup": "Cherub",
      "Fußes leuchte": "Fußes Leuchte",
      "berobbt": "beraubt",
      "Vereisung": "Verheißung",
      "Verheissung": "Verheißung",
      "Beheißungen": "Verheißung",
      "das gleiche": "das Gleiche",
      "Jeremias": "Jeremia",
      "Hiramia": "Jeremia",
      "Endzeitbotschaft": "Endzeit-Botschaft",
      "Anricht ": "Anrecht ",
      "Jeremiah": "Jeremia",
      "Malachi": "Maleachi",
      "Mariachi": "Maleachi",
      "Maliachi": "Maleachi",
      "Maliache": "Maleachi",
      "mit betroffen": "mitbetroffen",
      "ein für alle Mal": "ein für allemal",
      "vorgestrickte": "vorgestreckte",
      "Glauben ins Wege": "Glaubenswege",
      "Elijah": "Elia",
      "Brusa Park": "Bruder Borg",
      "Bruder Bock": "Bruder Borg",
      " Bork": " Borg",
      "getarren": "getarnt",
      "Isäbel": "Isebel",
      "Gezimmer": "Gethsemane",
      "Garten gezimmerne": "Garten Gethsemane",
      "Seeligist": "seelig ist",
      "Bitte schön": "Bitteschön",
      "Brüße": "Buße",
      "Bereitwahren": "bereit waren",
      "Alttestamenten, ich heilige": "alttestamentenich Heiligen",
      "Knicht": "Knecht",
      "lieb gehabt": "liebgehabt",
      "neu belieben": "neu beleben",
      "Joshua": "Josua",
      " daß ": " dass ",
      "Mißgeschick": "Missgeschick",
      "Heiliger Name": "heiliger Name",
      "Kathrin Kullmann": "Kathryn Kuhlman",
      "Catherine Coleman": "Kathryn Kuhlman",
      "Gottesvolk": "Gottes Volk",
      "Verlendung": "Vollendung",
      "Galatte": "Galater",
      "Galaterbriefe": "Galater-Brief",
      "Galaterbrief": "Galater-Brief",
      "Epheserbriefe": "Epheser-Brief",
      "Epheserbrief": "Epheser-Brief",
      "Verlindung": "Vollendung",
      "Erweckungsversammlung": "Erweckungs-Versammlung",
      "Ämmeraus": "Emmaus",
      "ersten kommend": "ersten Kommen",
      "erste kommend": "erste Kommen",
      "Eglesia": "Ecclesia",
      " gebackt ": " gepackt ",
      "Rechtsendresse": "richtige Adresse",
      "Prenhems": "Branhams",
      "Gebietsanliegen": "Gebetsanliegen",
      "Brennhilm": "Branham",
      "Bruder Prenam": "Bruder Branham",
      "Bruder Prinem": "Bruder Branham",
      "Bruder Brinem": "Bruder Branham",
      "Bruder Bringen": "Bruder Branham",
      "Bruderprinim": "Bruder Branham",
      " ausgnaden": " aus Gnaden",
      " an Bietung ": " Anbetung ",
      " an Betung ": " Anbetung ",
      "An Betung ": "Anbetung ",
      " Anbietung ": " Anbetung ",
      "Hymnischer": "Himmlischer",
      "Himmelscher": "Himmlischer",
      "Hymnlicher": "Himmlischer",
      "Vergiebung": "Vergebung",
      "Nadel schenken": "Gnade schenken",
      "Lied der Dichter": "Liederdichter",
      "Verlängerung": "Vollendung",
      "Seemann": "Sämann",
      " und und getan": " und kundgetan",
      "Kunst getan": "kundgetan",
      "geöffentbart": "geoffentbart",
      "Bartholomeus": "Bartimäus",
      "Wuderbringim ": "Bruder Branham ",
      "Bruder Brin ": "Bruder Branham ",
      "Verländer": "Vollender",
      "Bruder Bremen ": "Bruder Branham ",
      "Essa, denn": "Es sei denn",
      "essa, denn": "es sei denn",
      " Wouter": " Bruder",
      "Sinsschreiben": "Sendschreiben",
      "Sinn Schreiben": "Sendschreiben",
      "Sinnschreiben": "Sendschreiben",
      "[BLANK_AUDIO]": " ",
      "Bruder Brenne ": "Bruder Branham ",
      "heiligen Schrift": "Heiligen Schrift",
      "papylonisch": "Babylonisch",
      "papylonischen": "Babylonischen",
      "Isak": "Isaak",
      "Isaac": "Isaak",
      "Isaks": "Isaaks",
      "Heiligen Geist": "heiligen Geist",
      "Heilige Geist": "heilige Geist",
      "Herrscherin": "Heerscharen",
      "Prophet Hagein": "Prophet Haggai",
      "Finsenis": "Finsternis",
      "Profiten": "Propheten",
      "Bruthaus": "Brothaus",
      "Lefiten": "Leviten",
      "Lefit": "Levit",
      "Braterus": "bratr Russ",
      "Bátharus": "bratr Russ",
      "Báthar": "bratr",
      "Verheizung": "Verheißung",
      "Erstmoses": "Erste Moses",
      "Morse": "Mose",
      "Muse ": "Mose ",
      "frumme ": "fromme ",
      "Joils": "Joels",
      "Bibelfers": "Bibelvers",
      "Bruderus": "Bruder Russ",
      "Udo Ross": "Bruder Russ",
      "Bruder Rusch": "Bruder Russ",
      "Puder Russ": "Bruder Russ",
      "puderös": "Bruder Russ",
      "Hodoros": "Bruder Russ",
      "Buderus": "Bruder Russ",
      "Bruder Ross": "Bruder Russ",
      "Bude Ross": "Bruder Russ",
      " Hiops": " Hiobs",
      " Hiop": " Hiob",
      "Weiss sagt": "weissagt",
      "Sehnschreiben": "Sendschreiben",
      "Destamens": "Testaments",
      "Destamen": "Testament",
      "Zaharias": "Sacharja",
      "Zakaria": "Sacharja",
      "Sagaria": "Sacharja",
      "Minghi": "Menge",
      "Olgath": "Golgatha",
      "Bölgata": "Golgatha",
      "Kolgata": "Golgatha",
      "Geistestapfel": "Geistestaufe",
      "hineingemogen": "hineingenommen",
      "Antimotheus": "an Timotheus",
      "Dämodius": "Timotheus",
      "Demotius": "Timotheus",
      "Demodius": "Timotheus",
      "Timodius": "Timotheus",
      "Imodius": "Timotheus",
      "Vorricht": "Vorrecht",
      "Herrscharen": "Heerscharen",
      "Würtenträger": "Würdenträger",
      "Heiliger Mond": "Heiliger Mund",
      "Mond Gottes": "Mund Gottes",
      "preis und Ehre": "Preis und Ehre",
      " Reis und Ehre": " Preis und Ehre",
      " Reis sei Gott": " Preis sei Gott",
      "neunteste männliche": "neutestamentliche",
      "neutesten männliche": "neutestamentliche",
      "neuesten männliche": "neutestamentliche",
      "neuteste männliche": "neutestamentliche",
      "neu-distamentliche": "neutestamentliche",
      "neudislamendliche": "neutestamentliche",
      "neudistamentlichen": "neutestamentlichen",
      "neudestamendliche": "neutestamentliche",
      "neudestamentliche": "neutestamentliche",
      "neudestamentlichen": "neutestamentlichen",
      "Neu-Destammtmännlichen": "neutestamentlichen",
      "Neu-Destammtmännliche": "neutestamentliche",
      "Neu-Destammtmännlich": "neutestamentlich",
      "Salamo": "Salomo",
      "neudistamentliche": "neutestamentliche",
      "Hebräerbrief": "Hebräer-Brief",
      "Korintherbrief": "Korinther-Brief",
      "Thessalonica": "Thessalonicher",
      "Testalonischer": "Thessalonicher",
      "bitten und fliehen": "bitten und flehen",
      "Bitten und Fliehen": "Bitten und Flehen",
      "überbitten": "über Bitten",
      " hinauf genommen ": " hinaufgenommen ",
      "da selbst": "daselbst",
      "quitschvidil": "quietschfidel",
      "Herzenshertigkeit": "Herzenshärtigkeit",
      "hinein zu sprechen": "hineinzusprechen",
      "Weiss sagen": "weissagen",
      "weiß sagte": "weissagte",
      "Weiß sagen": "weissagen",
      "Dienstbruder": "Dienst Bruder",
      "Wortbraut": "Wort-Braut",
      "Brotgemeinde": "Braut-Gemeinde",
      "Serubabel": "Serubbabel",
      "Sahariya": "Sacharja",
      "Sacharia": "Sacharja",
      "Hesikiel": "Hesekiel",
      "Hesäkel": "Hesekiel",
      "Epäse": "Epheser",
      "Logen Dank": "Lob und Dank",
      "Berg Nepo": "Berg Nebo",
      "Berge Nepo": "Berge Nebo",
      " Nepo ": " Nebo ",
      "Pelzebub": "Belzebub",
      "Pharisee": "Pharisäer",
      "Gnechte": "Knechte",
      "Geloft": "Gelobt",
      "Schickerien": "Shakarian",
      "Herrischer Vater": "Himmlischer Vater",
      "Hümmelscher": "Himmlischer",
      "Sibylon": "Sebulon",
      "Isachar": "Issaschar",
      "Dt": "5M",
      "Deuteronómium": "5M",
      "Exodus": "2M",
      "Genesis": "1M",
      "Genezis": "1M",
      "Leviticus": "3M",
      "Lefitten": "Leviten",
      "Stimmt's": "Stimmt es",
      "stimmt's": "stimmt es",
      "Durften's": "Durften es",
      "durften's": "durften es",
      "Numeri": "4M",
      "Laupötenfest": "Laubhüttenfest",
      "Laupöten": "Laubhütten",
      "Tonbinder": "Tonbänder",
      "Ahasferos": "Ahasveros",
      "Mardukai": "Mardochai",
      "Verstinknis": "Verständnis",
      "Gangst": "Geist",
      "Gangstes": "Geistes",
      "Gomorras": "Gomorrhas",
      "Vorbedienung": "Vorbedingung",
      "Freuer Gott": "Treuer Gott",
      "Bruder Nebel": "Bruder Neville",
      "Bruder Prene": "Bruder Branham",
      "Bruder Prelim": "Bruder Branham",
      "Bude Schmitt": "Bruder Schmidt",
      "Puder Schmitt": "Bruder Schmidt",
      "Puder Schmit": "Bruder Schmidt",
      "Puder Schmidt": "Bruder Schmidt",
      "Bruder Prems": "Bruder Branhams",
      " Prené ": " Branham ",
      "Bruder Premhim": "Bruder Branham",
      "Udo     Branham": "Bruder Branham",
      "Bruder Premiem": "Bruder Branham",
      "Bruder Brenner": "Bruder Branham",
      "Bude Branham": "Bruder Branham",
      "Bruder Prenim": "Bruder Branham",
      "Bruderruf": "Bruder Russ",
      "Bruder Rostan": "Bruder Russ",
      "Rudrus": "Bruder Russ",
      "in seinem Worten": "in seinem Worte",
      "In seinem Worten": "In seinem Worte",
      "Schriftstille": "Schriftstelle",
      "Bibelschelle": "Bibelstelle",
      "Bibelschille": "Bibelstelle",
      "Bibelstille": "Bibelstelle",
      "Reiß sei": "Preis sei",
      "geseibt": " gesalbt ",
      "Geseipte": "Gesalbte",
      "hinbegehen": "hinweggehen",
      "Sadduzeer": "Sadduzäer",
      "Nazarener": "Nazaräer",
      "Heilig-Sprechung": "Heiligsprechung",
      "so und so": "Soundso",
      "So und So": "Soundso",
      "Anklage Rede": "Anklagerede",
      "Budapremis": "Bruder Branhams",
      "Puderprinims": "Bruder Branhams",
      "Predigung der Pränens": "Predigt Bruder Branhams",
      "hindurch führen": "hindurchführen",
      "Bruder Scherer": "Bruder Schörer",
      "Gebetsgarten": "Gebetskarten",
      "Gebetsgarte": "Gebetskarte",
      "zweischnellige": "zweischneidige",
      "Gehorchsam ": "Gehorsam ",
      " Joseh ": " Josua ",
      "Jannis": "Jannes",
      "zerrottetem": "zerrüttetem",
      "zerrottet in": "zerrüttetem",
      "kommt getan": "kundgetan",
      "Röstzeug": "Rüstzeug",
      "Blut Islames": "Blut des Lammes",
      "Geweib": "Geweih",
      "Zacharia": "Sacharja",
      "Heilgottes": "Heil Gottes",
      "Wuder ": "Bruder ",
      "Kröppeln": "Krüppeln",
      "Pude ": "Bruder ",
      "Predigtbruder": "Predigt Bruder",
      "Priedi ": "Predigt ",
      "Zunamitin": "Sunamitin",
      "Tzunamitin": "Sunamitin",
      "Tsunamitin": "Sunamitin",
      "Heilsland": "Heilsplan",
      "Hains Ratschluss": "Heilratschluss",
      " ausgenaden": " aus Gnaden",
      "Knechtchristi": "Knecht Christi",
      "Knechtbruder": "Knecht Bruder",
      "Bruder Premium": "Bruder Branham",
      "Hierchos": "Jerichos",
      "Zacchaeus": "Zachäus",
      "verfendet": "verpfändet",
      " unsret ": " unseret ",
      "Mond des Propheten": "Mund des Propheten",
      "hoher Priester": "Hohepriester",
      " muß ": " muss ",
      " ersten Moses": " 1. Moses",
      "Parallelstille": "Parallelstelle",
      " zweiten Korinther": " 2. Korinther",
      " erste Korinther": " 1. Korinther",
      " ersten Kapitel": " 1. Kapitel",
      " erste Kapitel": " 1. Kapitel",
    };

    if (language == "en") {
      replacements.addAll(replacements_en);
    } else if (language == "sk") {
      replacements.addAll(replacements_sk);
    } else if (language == "de") {
      replacements.addAll(replacements_de);
    } else {
      replacements.addAll(replacements_de);
      replacements.addAll(replacements_sk);
      replacements.addAll(replacements_en);
    }
    replacements.forEach((old, replacement) {
      text = text.replaceAll(old, replacement);
    });

    text = text.replaceAll(
        RegExp(
          r"(Brinhems|Pränenz|Branhamies|Prennems|Pridims|Prehnems|Prenhems|Pränims|Brünnhems|Brennhams|Pränens|Prehens|Brennums|Brannhams|Brennims|Brenhams|Brinhems|Prennims|Prenims|Brennems|Brennams|Brynhems)"),
        "Branhams");
    text = text.replaceAll(
        RegExp(
            r"(Brinhem|Prennem|Prenhim|Branheim|Brigham|Pringim|Brenem|Brünnhild|Brennwort|Brehnen|Brynhem|Prenhjem|Brenhim|Brennhim|Brynhim|Prennep|Brünnhem|Prenhem|Pränim|Branhamd|Brenhen|Brehnem|Prennheim|Prenem|Prinim|Prennim|Prenheim|Brunheim|Prennum|Brennum|Brenhem|Brennen|Brenheim|Brinham|Brannham|Brennem|Brennhelm|Brinim|Brinhelm|Brinheim|Brennheim|Brunham|Brinhim|Brennhem|Brangham|Brenham|Brennan|Brnham|Brannan|Brannam|Brahm|Brennim|Bredem|Brinnen|Brenni)"),
        "Branham");

    return text;
  }
}
